### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by uwe-schwarz** [hoffie/dkb-visa#3]
I get the following trace when starting:

Traceback (most recent call last):
  File "/home/uwe/dkb-banking/dkb-visa/dkb.py", line 413, in <module>
    fetcher.login(args.userid, pin)
  File "/home/uwe/dkb-banking/dkb-visa/dkb.py", line 61, in login
    br.form = list(br.forms())[0]
IndexError: list index out of range

**Comment by hoffie** [comment]
Thanks for the report. I am not using this package daily and did not notice it until now.

The issue is caused by a syntax error in DKB's HTML, which confuses even the error-tolerant mechanize and beautifulsoup libs. I see no sane way besides manually fixing this. As you can see, I have just committed a workaround, which does exactly this. I will also try to reach out to dkb if they intend to fix this on their side so that we can drop the fix again.

See https://validator.w3.org/nu/?doc=https%3A%2F%2Fbanking.dkb.de%2Fdkb%2F-%3F%24javascript%3Ddisabled list item 13. The broken IE conditional comment `<![endif-->` probably makes mechanize interpret the whole document as part of this "comment" so that there is no real content left.

**Comment by uwe-schwarz** [comment]
Thanks for debugging. I just tested the fix and it works perfectly.
